---
permalink: protect-hana/task_clone_sap_hana_database_backups_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: O fluxo de trabalho do clone inclui Planejamento, execução da operação do clone e monitoramento da operação. 
---
= Clonar backups de bancos de dados do SAP HANA usando cmdlets do PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O fluxo de trabalho do clone inclui Planejamento, execução da operação do clone e monitoramento da operação.

Você deve ter preparado o ambiente do PowerShell para executar os cmdlets do PowerShell.

As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets-50/index.htmll["Guia de referência de cmdlet do software SnapCenter"^].

.Passos
. Inicie uma sessão de conexão com o servidor SnapCenter para um usuário especificado usando o cmdlet Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Recupere os backups para executar a operação de clone usando o cmdlet Get-SmBackup.
+
Este exemplo mostra que dois backups estão disponíveis para clonagem:

+
[listing]
----
 C:\PS> Get-SmBackup

        BackupId                      BackupName                    BackupTime                    BackupType
        --------                      ----------                    ----------                    ----------
         1                     Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM          Full Backup
         2                     Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
. Inicie uma operação de clone a partir de um backup existente e especifique os endereços IP de exportação NFS nos quais os volumes clonados são exportados.
+
Este exemplo mostra que o backup a ser clonado tem um endereço NFSExportIPs de 10.232.206.169:

+
[listing]
----
New-SmClone -AppPluginCode hana -BackupName scsccore1_sccore_test_com_hana_H73_scsccore1_06-07-2017_02.54.29.3817 -Resources @{"Host"="scsccore1.sccore.test.com";"Uid"="H73"}  -CloneToInstance shivscc4.sccore.test.com -mountcommand 'mount 10.232.206.169:%hana73data_Clone /hana83data' -preclonecreatecommands '/home/scripts/scpre_clone.sh' -postclonecreatecommands '/home/scripts/scpost_clone.sh'
----
+

NOTE: Se NFSExportIPs não for especificado, o padrão será exportado para o host de destino clone.

. Verifique se os backups foram clonados com sucesso usando o cmdlet Get-SmCloneReport para exibir os detalhes da tarefa clone.
+
Você pode exibir detalhes como ID do clone, data e hora de início, data e hora de término.

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

    SmCloneId           : 1
    SmJobId             : 186
    StartDateTime       : 8/3/2015 2:43:02 PM
    EndDateTime         : 8/3/2015 2:44:08 PM
    Duration            : 00:01:06.6760000
    Status              : Completed
    ProtectionGroupName : Draper
    SmProtectionGroupId : 4
    PolicyName          : OnDemand_Clone
    SmPolicyId          : 4
    BackupPolicyName    : OnDemand_Full_Log
    SmBackupPolicyId    : 1
    CloneHostName       : SCSPR0054212005.mycompany.com
    CloneHostId         : 4
    CloneName           : Draper__clone__08-03-2015_14.43.53
    SourceResources     : {Don, Betty, Bobby, Sally}
    ClonedResources     : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER, Sally_DRAPER}
    SmJobError          :
----

