---
permalink: protect-scc/task_back_up_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: backup resources 
summary: Fazer backup de um recurso inclui estabelecer uma conexão com o servidor SnapCenter, adicionar recursos, adicionar uma política, criar um grupo de recursos de backup e fazer backup. 
---
= Faça backup de recursos usando cmdlets do PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fazer backup de um recurso inclui estabelecer uma conexão com o servidor SnapCenter, adicionar recursos, adicionar uma política, criar um grupo de recursos de backup e fazer backup.

.Antes de começar
* Você deve ter preparado o ambiente do PowerShell para executar os cmdlets do PowerShell.
* Você deve ter adicionado a conexão do sistema de armazenamento e criado uma credencial.


.Sobre esta tarefa
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _get-Help command_name_. Em alternativa, pode também consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets-50/index.html["Guia de referência de cmdlet do software SnapCenter"^].

.Passos
. Inicie uma sessão de conexão com o servidor SnapCenter para um usuário especificado usando o cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
É apresentado o aviso de nome de utilizador e palavra-passe.

. Adicione recursos usando o cmdlet Add-SmResources.
+
Este exemplo adiciona recursos:

+
[listing]
----
Add-SmResource -HostName '10.232.206.248' -PluginCode 'DB2' -ResourceName NONREC1 -ResourceType Database -StorageFootPrint ( @
{"VolumeName"="DB2_NONREC1DB";"LunName"="DB2_NONREC1DB";"Vserver"="vserver_scauto_secondary"}) -Instance db2inst1
----
. Crie uma política de backup usando o cmdlet Add-SmPolicy.
+
Este exemplo cria uma nova política de backup:

+
[listing]
----
Add-SMPolicy -PolicyName 'db2VolumePolicy' -PolicyType 'Backup' -PluginPolicyType DB2  -description 'VolumePolicy'
----
. Adicione um novo grupo de recursos ao SnapCenter usando o cmdlet Add-SmResourceGroup.
+
Este exemplo cria um novo grupo de recursos com a política e os recursos especificados:

+
[listing]
----
Add-SmResourceGroup -ResourceGroupName 'Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix' -Resources @(@
{"Host"="10.232.206.248";"Uid"="db2inst2\NONREC"},@{"Host"="10.232.206.248";"Uid"="db2inst1\NONREC"}) -Policies db2ManualPolicy
----
. Inicie uma nova tarefa de backup usando o cmdlet New-SmBackup.
+
[listing]
----
New-SMBackup -DatasetName Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix -Policy db2ManualPolicy
----
. Exiba o status da tarefa de backup usando o cmdlet Get-SmBackupReport.
+
Este exemplo exibe um relatório de resumo de todos os trabalhos executados na data especificada:

+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----

